export const ThirdPartyRewardsData = [
  {
    _id: '1',
    title: 'Spotify Premium 1 Month',
    description: 'Enjoy 1 month of Spotify Premium for free.',
    image: '/images/rewards/spotify.png',
    pointCost: 500,
    claimLimit: 1,
    statusLimit: 'Gold',
    rewardSourceLink: 'https://api.spotify.com/redeem',
    publicKeyForPartner: 'SPOTIFY_PUBLIC_KEY_123',
  },
  {
    _id: '2',
    title: 'Amazon Gift Card - $10',
    description: 'Redeem a $10 Amazon Gift Card instantly.',
    image: '/images/rewards/amazon.png',
    pointCost: 1000,
    claimLimit: 2,
    statusLimit: 'Silver',
    rewardSourceLink: 'https://api.amazon.com/redeem',
    publicKeyForPartner: 'AMAZON_PUBLIC_KEY_456',
  },
  {
    _id: '3',
    title: 'Netflix 1 Week Pass',
    description: 'Get a free 1-week Netflix streaming pass.',
    image: '/images/rewards/netflix.png',
    pointCost: 750,
    claimLimit: 1,
    statusLimit: 'Bronze',
    rewardSourceLink: 'https://api.netflix.com/redeem',
    publicKeyForPartner: 'NETFLIX_PUBLIC_KEY_789',
  },
];
