import { BrandOption, MenuItemRecord, MenuOption } from './types';

// Categories/subcategories are now owned by the menuSubcategories module — re-exported here to keep a single source of truth.
export { mockCategories, mockSubcategories } from '../menuSubcategories/data';

// Preset types are now owned by the preset-types module — re-exported here to keep a single source of truth.
export { mockPresetTypes } from '../preset-types/data';

// TODO(v2-api): replace with real menu data once the backend endpoint is ready.
export const mockMenus: MenuOption[] = [
  { _id: 'menu-1', title: 'Summer Menu 2026' },
  { _id: 'menu-2', title: 'Winter Menu 2025' },
  { _id: 'menu-3', title: 'Event Menu — Black Swan' },
  { _id: 'menu-4', title: 'Happy Hour Menu' },
];

// TODO(v2-api): replace with real brand data once the backend endpoint is ready.
export const mockBrands: BrandOption[] = [
  { _id: 'brand-1', label: "Hendrick's" },
  { _id: 'brand-2', label: 'San Pellegrino' },
  { _id: 'brand-3', label: 'Aperol' },
];

// TODO(v2-api): replace with real menu item data once the backend endpoint is ready.
export const mockMenuItemsData: MenuItemRecord[] = [
  {
    _id: 'item-1',
    title: 'Adriatic Sunset',
    amount: '200ml',
    presetTypeId: 'preset-1',
    subcategoryId: 'subcat-1',
    menuIds: ['menu-1'],
    quantityType: 'single',
    serving: 'glass',
    price: 12.0,
    taxPercent: 25,
    availableDays: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'],
    daypart: ['dinner'],
    status: 'active',
    createdAt: '2026-06-01',
  },
  {
    _id: 'item-2',
    title: 'Sunset Combo',
    presetTypeId: 'preset-1',
    subcategoryId: 'subcat-1',
    menuIds: ['menu-1'],
    quantityType: 'combo',
    comboItemIds: ['item-1', 'item-3'],
    serving: 'combo',
    price: 18.0,
    taxPercent: 25,
    availableDays: ['fri', 'sat', 'sun'],
    daypart: ['dinner'],
    status: 'active',
    createdAt: '2026-06-01',
  },
  {
    _id: 'item-3',
    title: 'Bruschette al Pomodoro',
    presetTypeId: 'preset-3',
    subcategoryId: 'subcat-3',
    menuIds: ['menu-1'],
    quantityType: 'single',
    serving: 'sharing',
    price: 7.0,
    taxPercent: 13,
    availableDays: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'],
    daypart: ['lunch', 'dinner'],
    dietTags: ['vegetarian'],
    status: 'active',
    createdAt: '2026-06-01',
  },
  {
    _id: 'item-4',
    title: 'Champagne Top-up',
    amount: '150ml',
    presetTypeId: 'preset-4',
    brandId: 'brand-2',
    subcategoryId: 'subcat-2',
    menuIds: ['menu-1'],
    quantityType: 'single',
    serving: 'glass',
    price: 8.0,
    taxPercent: 25,
    availableDays: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'],
    daypart: ['dinner'],
    isUpsell: true,
    status: 'active',
    createdAt: '2026-06-01',
  },
  {
    _id: 'item-5',
    title: 'Winter Spritz',
    amount: '180ml',
    presetTypeId: 'preset-1',
    subcategoryId: 'subcat-1',
    menuIds: ['menu-1'],
    quantityType: 'single',
    serving: 'glass',
    price: 10.0,
    taxPercent: 25,
    availableDays: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'],
    daypart: ['dinner'],
    status: 'inactive',
    createdAt: '2026-05-20',
  },
  {
    _id: 'item-6',
    title: 'Aperol Spritz',
    amount: '200ml',
    presetTypeId: 'preset-2',
    brandId: 'brand-3',
    subcategoryId: 'subcat-1',
    menuIds: ['menu-1'],
    quantityType: 'single',
    serving: 'glass',
    price: 9.0,
    taxPercent: 25,
    availableDays: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'],
    daypart: ['dinner'],
    status: 'active',
    createdAt: '2026-06-01',
  },
  {
    _id: 'item-7',
    title: 'Mojito',
    amount: '250ml',
    presetTypeId: 'preset-2',
    subcategoryId: 'subcat-1',
    menuIds: ['menu-1'],
    quantityType: 'single',
    serving: 'glass',
    price: 10.0,
    taxPercent: 25,
    availableDays: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'],
    daypart: ['dinner'],
    status: 'active',
    createdAt: '2026-06-01',
  },
  {
    _id: 'item-8',
    title: 'Margarita',
    amount: '200ml',
    presetTypeId: 'preset-2',
    subcategoryId: 'subcat-1',
    menuIds: ['menu-1'],
    quantityType: 'single',
    serving: 'glass',
    price: 11.0,
    taxPercent: 25,
    availableDays: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'],
    daypart: ['dinner'],
    status: 'active',
    createdAt: '2026-06-01',
  },
  {
    _id: 'item-9',
    title: 'Negroni',
    amount: '150ml',
    presetTypeId: 'preset-2',
    subcategoryId: 'subcat-1',
    menuIds: ['menu-1'],
    quantityType: 'single',
    serving: 'glass',
    price: 9.5,
    taxPercent: 25,
    availableDays: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'],
    daypart: ['dinner'],
    status: 'active',
    createdAt: '2026-06-01',
  },
  {
    _id: 'item-10',
    title: 'Malvazija 0.75l',
    presetTypeId: 'preset-4',
    subcategoryId: 'subcat-2',
    menuIds: ['menu-1'],
    quantityType: 'single',
    serving: 'bottle',
    price: 22.0,
    taxPercent: 25,
    availableDays: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'],
    daypart: ['dinner'],
    status: 'active',
    createdAt: '2026-06-01',
  },
  {
    _id: 'item-11',
    title: 'Plavac Mali 0.75l',
    presetTypeId: 'preset-4',
    subcategoryId: 'subcat-2',
    menuIds: ['menu-1'],
    quantityType: 'single',
    serving: 'bottle',
    price: 26.0,
    taxPercent: 25,
    availableDays: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'],
    daypart: ['dinner'],
    status: 'active',
    createdAt: '2026-06-01',
  },
];
