export const ReferralData = [
  {
    _id: '1',
    user: 'John Doe',
    referrer: 'Jane Smith',
    refLimit: 10,
    refCount: 4,
    totalRefs: 25,
    userPoints: 120,
    refPoints: 300,
    status: 'active',
    createdAt: '23-02-2024',
  },
  {
    _id: '2',
    user: 'Alice Brown',
    referrer: 'Michael Lee',
    refLimit: 15,
    refCount: 12,
    totalRefs: 40,
    userPoints: 200,
    refPoints: 450,
    status: 'inactive',
    createdAt: '23-02-2024',
  },
  {
    _id: '3',
    user: 'David Wilson',
    referrer: 'Sophia Green',
    refLimit: 20,
    refCount: 18,
    totalRefs: 55,
    userPoints: 340,
    refPoints: 600,
    status: 'active',
    createdAt: '23-02-2024',
  },
  {
    _id: '4',
    user: 'Emma Johnson',
    referrer: 'Chris Taylor',
    refLimit: 8,
    refCount: 7,
    totalRefs: 30,
    userPoints: 150,
    refPoints: 280,
    status: 'inactive',
    createdAt: '23-02-2024',
  },
];
