export const RewardsData = [
  {
    _id: '1',
    photo: '/images/menu/pizza.jpg',
    name: 'Pepperoni Pizza',
    description: 'Cheesy pizza topped with pepperoni slices.',
    type: 'Food',
    pointValue: 150,
    limit: 2,
    tierLimit: 'gold',
    percentOff: 20,
    creationMethod: 'menu-items',
    menuItems: ['pizza-1'],
    eventId: '',
  },
  {
    _id: '2',
    photo: '/images/menu/salad.jpg',
    name: 'Caesar Salad',
    description: 'Fresh romaine lettuce with Caesar dressing.',
    type: 'Food',
    pointValue: 80,
    limit: 5,
    tierLimit: 'silver',
    percentOff: 10,
    creationMethod: 'menu-items',
    menuItems: ['salad-1'],
    eventId: '',
  },
  {
    _id: '3',
    photo: '/images/menu/coffee.jpg',
    name: 'Cappuccino',
    description: 'Rich espresso with steamed milk foam.',
    type: 'Drink',
    pointValue: 60,
    limit: 10,
    tierLimit: 'bronze',
    percentOff: 0,
    creationMethod: 'menu-items',
    menuItems: ['coffee-1'],
    eventId: '',
  },
  {
    _id: '4',
    photo: '/images/menu/icecream.jpg',
    name: 'Vanilla Ice Cream',
    description: 'Classic vanilla ice cream scoop.',
    type: 'Dessert',
    pointValue: 50,
    limit: 3,
    tierLimit: 'gold',
    percentOff: 15,
    creationMethod: 'menu-items',
    menuItems: ['dessert-1'],
    eventId: '',
  },
  {
    _id: '5',
    photo: '/images/rewards/vip-entry.jpg',
    name: 'VIP Event Entry',
    description: 'Exclusive access to VIP area at special events.',
    type: 'Experience',
    pointValue: 300,
    limit: 1,
    tierLimit: 'gold',
    percentOff: 0,
    creationMethod: 'ticket',
    menuItems: [],
    eventId: 'event-1',
  },
  {
    _id: '6',
    photo: '/images/rewards/merchandise.jpg',
    name: 'Branded T-Shirt',
    description: 'Exclusive restaurant branded merchandise.',
    type: 'Merchandise',
    pointValue: 120,
    limit: 0,
    tierLimit: 'none',
    percentOff: 0,
    creationMethod: 'custom',
    menuItems: [],
    eventId: '',
  },
];
