import { Category } from './types';

export const initialCategories: Category[] = [
  {
    id: '1',
    name: 'Summer Specials',
    type: 'event-1',
    priority: 'priority-1',
    isPinned: true,
    isVisible: true,
    order: 1,
    itemCount: 12,
  },
  {
    id: '2',
    name: 'VIP Exclusive',
    type: 'event-1',
    priority: 'priority-1',
    isPinned: false,
    isVisible: false,
    order: 2,
    itemCount: 5,
  },
  {
    id: '3',
    name: 'Adventure Tours',
    type: 'event-1',
    priority: 'priority-1',
    isPinned: true,
    isVisible: true,
    order: 3,
    itemCount: 8,
  },
  {
    id: '4',
    name: 'Event Partners',
    type: 'event-1',
    priority: 'priority-1',
    isPinned: false,
    isVisible: true,
    order: 4,
    itemCount: 15,
  },
  {
    id: '5',
    name: 'Summer Specials 2',
    type: 'event-1',
    priority: 'priority-1',
    isPinned: true,
    isVisible: true,
    order: 1,
    itemCount: 12,
  },
];
