export const PresetData = [
  {
    _id: '1',
    name: 'Coca Cola 1.5L',
    status: 'active',
    createdAt: '10-06-2024',
    description: 'Juicy beef patty with lettuce, tomato, and cheese.',
    basePrice: 8.99,
  },
  {
    _id: '2',
    name: 'Pepsi 500ml',
    status: 'active',
    createdAt: '10-06-2024',
    description: 'Fresh greens, avocado, and nuts with vinaigrette.',
    basePrice: 5.49,
  },
  {
    _id: '3',
    name: 'Chicken Burger',
    status: 'active',
    createdAt: '10-06-2024',
    description: 'Fresh greens, avocado, and nuts with vinaigrette.',
    basePrice: 7.25,
  },
  {
    _id: '4',
    name: 'French Fries',
    status: 'active',
    createdAt: '10-06-2024',
    description: 'Fresh greens, avocado, and nuts with vinaigrette.',
    basePrice: 3.99,
  },
  {
    _id: '5',
    name: 'Veg Pizza',
    status: 'active',
    createdAt: '10-06-2024',
    description: 'Fresh greens, avocado, and nuts with vinaigrette.',
    basePrice: 9.75,
  },
  {
    _id: '6',
    name: 'Grilled Sandwich',
    status: 'active',
    createdAt: '10-06-2024',
    description: 'Fresh greens, avocado, and nuts with vinaigrette.',
    basePrice: 6.50,
  },
];
