



export const eventData = [
  {
    id: '1',
    image: '/assets/images/event1.jpg',
    name: 'Tech Summit 2025',
    venue: 'Expo Center, Lahore',
    organizaiton: 'InnovateX',
    fromDate: '2025-08-01',
    endDate: '2025-08-03',
  },
  {
    id: '2',
    image: '/assets/images/event2.jpg',
    name: 'AI World Conference',
    venue: 'Convention Hall, Karachi',
    organizaiton: 'AI Future Lab',
    fromDate: '2025-09-12',
    endDate: '2025-09-14',
  },
  {
    id: '3',
    image: '/assets/images/event3.jpg',
    name: 'Startup Expo',
    venue: 'Nishtar Park, Islamabad',
    organizaiton: 'Startup Hub',
    fromDate: '2025-07-20',
    endDate: '2025-07-21',
  },
  {
    id: '4',
    image: '/assets/images/event4.jpg',
    name: 'Blockchain Fest',
    venue: 'Tech Park, Karachi',
    organizaiton: 'BlockChain PK',
    fromDate: '2025-08-18',
    endDate: '2025-08-19',
  },
  {
    id: '5',
    image: '/assets/images/event5.jpg',
    name: 'Digital Marketing Bootcamp',
    venue: 'Online',
    organizaiton: 'MarketMinds',
    fromDate: '2025-10-05',
    endDate: '2025-10-10',
  },
  {
    id: '6',
    image: '/assets/images/event6.jpg',
    name: 'Web Dev Meetup',
    venue: 'Arfa Tech Park, Lahore',
    organizaiton: 'CodeCraft',
    fromDate: '2025-11-01',
    endDate: '2025-11-01',
  },
  {
    id: '7',
    image: '/assets/images/event7.jpg',
    name: 'Cloud Computing Seminar',
    venue: 'University of Peshawar',
    organizaiton: 'CloudTech',
    fromDate: '2025-08-25',
    endDate: '2025-08-25',
  },
  {
    id: '8',
    image: '/assets/images/event8.jpg',
    name: 'Women in Tech',
    venue: 'Fatima Jinnah Auditorium',
    organizaiton: 'WomenTechPK',
    fromDate: '2025-09-18',
    endDate: '2025-09-18',
  },
  {
    id: '9',
    image: '/assets/images/event9.jpg',
    name: 'Cyber Security Summit',
    venue: 'NED University, Karachi',
    organizaiton: 'SecureNet',
    fromDate: '2025-12-01',
    endDate: '2025-12-02',
  },
  {
    id: '10',
    image: '/assets/images/event10.jpg',
    name: 'Green Energy Conference',
    venue: 'Serena Hotel, Islamabad',
    organizaiton: 'GreenFuture Org',
    fromDate: '2025-10-15',
    endDate: '2025-10-16',
  }
];
