export const RewardsData = [
  {
    username: 'JohnDoe',
    currentTier: 'Gold',
    status: 'Active',
    currentPointBalance: 1200,
    membershipStartDate: '2023-03-15',
    highestTierAchieved: 'Platinum',
    referralCount: 5,
    streak: 12,
    totalPointsEarned: 15000,
    totalPointsRedeemed: 13800,
    averagePointsPerMonth: 1250,
    totalTrackedSpending: 3200,
    totalTransactions: 45,
    actions: '',
  },
  {
    username: 'JaneSmith',
    currentTier: 'Silver',
    status: 'Inactive',
    currentPointBalance: 450,
    membershipStartDate: '2022-11-02',
    highestTierAchieved: 'Gold',
    referralCount: 2,
    streak: 3,
    totalPointsEarned: 5000,
    totalPointsRedeemed: 4550,
    averagePointsPerMonth: 400,
    totalTrackedSpending: 1100,
    totalTransactions: 18,
    actions: '',
  },
  {
    username: 'AlexLee',
    currentTier: 'Bronze',
    status: 'Active',
    currentPointBalance: 300,
    membershipStartDate: '2024-01-20',
    highestTierAchieved: 'Silver',
    referralCount: 1,
    streak: 5,
    totalPointsEarned: 900,
    totalPointsRedeemed: 600,
    averagePointsPerMonth: 200,
    totalTrackedSpending: 350,
    totalTransactions: 7,
    actions: '',
  },
];
