"use client"
import { Geist, Geist_Mono, Josefin_Sans, Poppins } from "next/font/google";
import "./globals.css";
import { metadata } from './metadata'
import { ThemeProvider } from "@/components/templates/theme-provider";
import { Provider } from "react-redux";
import { store } from "@/store/store";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600"],
  subsets: ["latin"],
});

const josefin = Josefin_Sans({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// export { metadata }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.variable} ${josefin.variable} antialiased`}
      >
        <Provider store={store}>

          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem={true}
            disableTransitionOnChange={false}
          >
            {children}
          </ThemeProvider>
        </Provider>
      </body>
    </html>
  );
}
