'use client';
import AuthProvider from '@/components/providers/AuthProvider';
import { ThemeProvider } from '@/components/templates/theme-provider';
import { store } from '@/store/store';
import { Inter } from 'next/font/google';
import { useEffect } from 'react';
import { usePathname } from 'next/navigation';
import { Provider } from 'react-redux';
import './globals.css';
import { Toaster } from 'react-hot-toast';

import 'react-phone-input-2/lib/style.css';

// const poppins = Poppins({
//   variable: "--font-poppins",
//   weight: ["100", "200", "300", "400", "500", "600"],
//   subsets: ["latin"],
// });

// const josefin = Josefin_Sans({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const inter = Inter({
  variable: '--font-inter',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// export { metadata }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  useEffect(() => {
    if (typeof window !== 'undefined') {
      window.scrollTo({ top: 0, behavior: 'smooth' });
    }
  }, [pathname]);

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} antialiased`}
        suppressHydrationWarning
      >
        <Toaster position="top-right" />
        <Provider store={store}>
          <AuthProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem={true}
              disableTransitionOnChange={false}
            >
              {children}
            </ThemeProvider>
          </AuthProvider>
        </Provider>
      </body>
    </html>
  );
}
