export const RewardsData = [
  {
    id: '1',
    photo: '/images/menu/burger.jpg',
    title: 'Burger Bonanza',
    description: 'Buy one get one free on all burgers.',
    startTime: '2024-07-01',
    endTime: '2024-07-07',
    tierLimit: 'Silver',
    repeatSettings: 'Weekly',
    type: 'Happy Hour',
  },
  {
    id: '2',
    photo: '/images/menu/salad.jpg',
    title: 'Healthy Salad Days',
    description: '20% off on all salads.',
    startTime: '2024-07-05',
    endTime: '2024-07-10',
    tierLimit: 'Gold',
    repeatSettings: 'Monthly',
    type: 'Happy Hour',
  },
  {
    id: '3',
    photo: '/images/menu/icecream.jpg',
    title: 'Ice Cream Fiesta',
    description: 'Free topping with every ice cream.',
    startTime: '2024-07-03',
    endTime: '2024-07-15',
    tierLimit: 'Platinum',
    repeatSettings: 'None',
    type: 'Happy Hour',
  },
];
