

export const organizationListData = [
    {
        id: 1,
        image: "https://via.placeholder.com/48x48.png?text=Org+1",
        name: "TechNova Inc.",
        phone: "+1 (555) 123-4567",
        email: "contact@technova.com",
        createdAt: "2023-01-15",
        status: "active",
        subscriptionType: "Premium User",
        subscriptionValidity: "2024-12-31",
        commission: "10%",
        totalRevenue: "$100,000",
        totalViews: 5,
        region: "North America"
    },
    {
        id: 2,
        image: "https://via.placeholder.com/48x48.png?text=Org+2",
        name: "GreenWorks Ltd.",
        phone: "+1 (555) 987-6543",
        email: "hello@greenworks.io",
        createdAt: "2022-11-10",
        status: "inactive",
        subscriptionType: "Basic User",
        subscriptionValidity: "2023-11-10",
        commission: "12%",
        totalRevenue: "$50,000",
        totalViews: 3,
        region: "Europe"
    },
    {
        id: 3,
        image: "https://via.placeholder.com/48x48.png?text=Org+3",
        name: "EduSmart Co.",
        phone: "+1 (555) 222-3344",
        email: "support@edusmart.org",
        createdAt: "2024-03-05",
        status: "active",
        subscriptionType: "Enterprise User",
        subscriptionValidity: "2025-03-05",
        commission: "15%",
        totalRevenue: "$75,000",
        totalViews: 4,
        region: "Asia"
    },
    {
        id: 4,
        image: "https://via.placeholder.com/48x48.png?text=Org+4",
        name: "Healthify Global",
        phone: "+1 (555) 777-8888",
        email: "info@healthify.com",
        createdAt: "2023-08-22",
        status: "active",
        subscriptionType: "Premium User",
        subscriptionValidity: "Lifetime",
        commission: "8%",
        totalRevenue: "$200,000",
        totalViews: 10,
        region: "Australia"
    },
    {
        id: 5,
        image: "https://via.placeholder.com/48x48.png?text=Org+5",
        name: "AgroTech Pvt. Ltd.",
        phone: "+92 300 1234567",
        email: "contact@agrotech.pk",
        createdAt: "2022-06-18",
        status: "inactive",
        subscriptionType: "Basic User",
        subscriptionValidity: "2023-06-18",
        commission: "7%",
        totalRevenue: "$30,000",
        totalViews: 2,
        region: "Pakistan"
    },
    {
        id: 6,
        image: "https://via.placeholder.com/48x48.png?text=Org+6",
        name: "Logix Corp.",
        phone: "+1 (555) 444-3322",
        email: "team@logix.com",
        createdAt: "2023-05-01",
        status: "active",
        subscriptionType: "Enterprise User",
        subscriptionValidity: "2024-05-01",
        commission: "11%",
        totalRevenue: "$120,000",
        totalViews: 6,
        region: "South America"
    },
    {
        id: 7,
        image: "https://via.placeholder.com/48x48.png?text=Org+7",
        name: "BrightLabs",
        phone: "+1 (555) 101-2020",
        email: "labs@brightlabs.io",
        createdAt: "2021-12-12",
        status: "inactive",
        subscriptionType: "Basic User",
        subscriptionValidity: "2022-12-12",
        commission: "5%",
        totalRevenue: "$40,000",
        totalViews: 1,
        region: "Middle East"
    },
    {
        id: 8,
        image: "https://via.placeholder.com/48x48.png?text=Org+8",
        name: "MediaSpark",
        phone: "+1 (555) 999-9999",
        email: "media@sparkmail.com",
        createdAt: "2023-09-09",
        status: "active",
        subscriptionType: "Premium User",
        subscriptionValidity: "2025-09-09",
        commission: "9%",
        totalRevenue: "$90,000",
        totalViews: 7,
        region: "Africa"
    },
    {
        id: 9,
        image: "https://via.placeholder.com/48x48.png?text=Org+9",
        name: "InnoSoft Solutions",
        phone: "+1 (555) 888-1111",
        email: "connect@innosoft.dev",
        createdAt: "2023-07-30",
        status: "active",
        subscriptionType: "Enterprise User",
        subscriptionValidity: "2024-07-30",
        commission: "13%",
        totalRevenue: "$150,000",
        totalViews: 8,
        region: "Europe"

    },
    {
        id: 10,
        image: "https://via.placeholder.com/48x48.png?text=Org+10",
        name: "SecurePay Inc.",
        phone: "+1 (555) 333-4455",
        email: "billing@securepay.net",
        createdAt: "2022-02-28",
        status: "inactive",
        subscriptionType: "Basic User",
        subscriptionValidity: "2023-02-28",
        commission: "6%",
        totalRevenue: "$25,000",
        totalViews: 2,

    },
];
