export const paths = {
  superAdmin: {
    default: '/super-admin',
    menu: '/super-admin/menu',
    invoices: '/super-admin/invoices',
    category: {
      default: '/super-admin/category',
      create: '/super-admin/category/create-category',
      list: '/super-admin/category/category-list',
    },
    hightLight: {
      default: '/super-admin/highlight',
      create: '/super-admin/highlight/create-highlight',
      list: '/super-admin/highlight/highlight-list',
    },
    tags: {
      default: '/super-admin/tags',
      create: '/super-admin/tags/create-tag',
      list: '/super-admin/tags/tag-list',
    },
    organizations: {
      default: '/super-admin/organization',
      create: '/super-admin/organization/create-organization',
      list: '/super-admin/organization/organization-list',
    },
    users: {
      default: '/super-admin/user',
      create: '/super-admin/user/create-user',
      list: '/super-admin/user/user-list',
      pendingList: '/super-admin/user/pending-list',
    },
    events: {
      default: '/super-admin/events',
      create: '/super-admin/events/create-event',
      list: '/super-admin/events/event-list',
    },
    update: {
      default: '/super-admin/update',
      create: '/super-admin/update/create-update',
      list: '/super-admin/update/update-list',
    },
    venue: {
      default: '/super-admin/venue',
      create: '/super-admin/venue/create-venue',
      list: '/super-admin/venue/venue-list',
    },
    venueType: {
      default: '/super-admin/venue-type',
      create: '/super-admin/venue-type/create',
      list: '/super-admin/venue-type/venue-type-list',
    },
    suppliers: {
      default: '/super-admin/suppliers',
      create: '/super-admin/suppliers/create',
      list: '/super-admin/suppliers/supplier-list',
    },
    userAccess: {
      default: '/super-admin/user-access',
      create: '/super-admin/user-access/create',
      list: '/super-admin/user-access/user-access-list',
    },
    region: {
      default: '/super-admin/region',
      create: '/super-admin/region/create-region',
      list: '/super-admin/region/region-list',
    },
    marketing: {
      detault: '/super-admin/marketing',
      create: '/super-admin/marketing/create-marketing',
      list: '/super-admin/marketing/marketing-list',
    },
    transactions: {
      default: '/super-admin/transactions',
    },
    globalTransactions: {
      default: '/super-admin/global-transactions',
    },
    terms: {
      default: '/super-admin/terms',
    },
    preset: {
      default: '/super-admin/preset',
    },
    browserControl: {
      default: '/super-admin/browser-control',
    },
    notification: {
      default: '/super-admin/notification',
      overview: '/super-admin/notification/overview',
      list: '/super-admin/notification/list',
      createUpdate: '/super-admin/notification/create-update',
      createGiveaway: '/super-admin/notification/create-giveaway',
      createNotification: '/super-admin/notification/create-notification',
    },
    globalLoyalty: {
      default: '/super-admin/global-loyalty',
    },

    globalRewards: '/super-admin/global-rewards',
    // globalThirdParty: '/super-admin/global-third-party',
    globalChallenges: '/super-admin/global-challenges',
    globalPromotions: '/super-admin/global-promotions',
    globalReferrals: '/super-admin/global-referrals',
    globalReferralsAnalytics: '/super-admin/global-referrals/analytics',

    loyalty: {
      default: '/super-admin/loyalty',
    },
    menuItems: '/super-admin/menuItems',
    menuList: '/super-admin/menu-list',
    menuSubcategories: '/super-admin/menu-subcategories',
    discounts: '/super-admin/discounts',
    combos: '/super-admin/combos',
    presetTypes: '/super-admin/preset-types',
    brands: '/super-admin/brands',
    serving: '/super-admin/serving',
    dietTags: '/super-admin/diet-tags',
    allergens: '/super-admin/allergens',
    daypart: '/super-admin/daypart',
    subcategoryTypes: '/super-admin/subcategory-types',

    // Ticketing and Reservation Paths
    ticketing: '/super-admin/ticketing',
    ticketingTransactions: '/super-admin/ticketing-transactions',
    reservation: '/super-admin/reservation',
    reservationV2: '/super-admin/reservation-v2',
    reservationPreferences: '/super-admin/reservation-preferences',
    analytics: '/super-admin/analytics',
    calendar: '/super-admin/calendar',
    reservationTransactions: '/super-admin/res-transactions',
    // reservationTransactions: '/super-admin/reservations/transactions',
    transactionsHistory: '/super-admin/transactions-history',
    bundles: '/super-admin/bundles',

    // App Ordering Paths
    orderManagement: '/super-admin/app-ordering/order-management',
    orderManagementV2: '/super-admin/app-ordering/order-management-v2',
    menuManagement: '/super-admin/app-ordering/menu-management',
    orderAnalytics: '/super-admin/app-ordering/order-analytics',
    orderSettings: '/super-admin/app-ordering/order-settings',
    orderSettingsV2: '/super-admin/app-ordering/order-settings-v2',
    orderTransactions: '/super-admin/app-ordering/order-transactions',

    qrCodes: '/super-admin/qr-codes',
    levelStatus: '/super-admin/level-status',
    promoCodes: '/super-admin/promo-code',
    rewardCategory: '/super-admin/reward-category',
    reviews: '/super-admin/reviews',

    faqs: '/super-admin/faqs',
    streak: '/super-admin/streaks',
    helpSupport: '/super-admin/help-support',
    updates: '/super-admin/updates',
    giveaways: '/super-admin/giveaways',
    globalNotification: '/super-admin/global-notification',
    globalNotificationAnalytics: '/super-admin/notification-analytics',
    marketingRequests: '/super-admin/marketing-requests',
    globalStreak: '/super-admin/global-streaks',
    itemsCategory: '/super-admin/items-category',
    status: '/super-admin/status',
    rewards: '/super-admin/rewards',
    challenges: '/super-admin/challenges',
    promotions: '/super-admin/promotions',
    members: '/super-admin/members',
    settings: '/super-admin/settings',
    referrals: '/super-admin/referrals',
    referralsAnalytics: '/super-admin/referrals/analytics',
    tiers: '/super-admin/tiers',
    thirdParty: '/super-admin/third-party',
    subscription: '/super-admin/subscription',
    addSupport: '/super-admin/add-support',
    tagType: '/super-admin/tag-type',
    logout: '/super-admin/logout',
  },
};
