export const RewardsData = [
  {
    id: '1',
    photo: '/images/menu/pizza.jpg',
    name: 'Pepperoni Pizza',
    description: 'Cheesy pizza topped with pepperoni slices.',
    type: 'Food',
    pointValue: 150,
    limit: 2,
    tierLimit: 'Gold',
    percentOff: 20,
  },
  {
    id: '2',
    photo: '/images/menu/salad.jpg',
    name: 'Caesar Salad',
    description: 'Fresh romaine lettuce with Caesar dressing.',
    type: 'Food',
    pointValue: 80,
    limit: 5,
    tierLimit: 'Silver',
    percentOff: 10,
  },
  {
    id: '3',
    photo: '/images/menu/coffee.jpg',
    name: 'Cappuccino',
    description: 'Rich espresso with steamed milk foam.',
    type: 'Drink',
    pointValue: 60,
    limit: 10,
    tierLimit: 'Bronze',
    percentOff: 5,
  },
  {
    id: '4',
    photo: '/images/menu/icecream.jpg',
    name: 'Vanilla Ice Cream',
    description: 'Classic vanilla ice cream scoop.',
    type: 'Dessert',
    pointValue: 50,
    limit: 3,
    tierLimit: 'Gold',
    percentOff: 15,
  },
];
