export const paths = {
  organizer: {
    default: '/organizer',
    menu: '/organizer/menu',
    invoices: '/organizer/invoices',
    calendar: '/organizer/calendar',
    dashboard: '/organizer/dashboard',
    menuItems: '/organizer/menuItems',
    rewards: '/organizer/rewards',
    challenges: '/organizer/challenges',
    promotions: '/organizer/promotions',
    referrals: '/organizer/referrals',
    members: '/organizer/members',
    home: '/organizer/home',
    tags: '/organizer/tags',
    loyalty: {
      default: '/organizer/loyalty',
      create: '/organizer/loyalty/create-loyalty',
      list: '/organizer/loyalty/loyalty-list',
    },
    boost: '/organizer/boost',
    settings: '/organizer/settings',
    organizations: {
      default: '/orgnizer/organization',
      create: '/organizer/organization/create-organization',
      list: '/organizer/organization/organization-list',
    },
    events: {
      default: '/organizer/events',
      create: '/organizer/events/create-event',
      list: '/organizer/events/event-list',
    },
    venue: {
      default: '/organizer/venue',
      create: '/organizer/venue/create-venue',
      list: '/organizer/venue/venue-list',
    },
    hightLight: {
      default: '/organizer/highlight',
      create: '/organizer/highlight/create-highlight',
      list: '/organizer/highlight/highlight-list',
    },
    marketing: {
      detault: '/organizer/marketing',
      create: '/organizer/marketing/create-marketing',
      list: '/organizer/marketing/marketing-list',
    },
    subscription: '/organizer/subscription',
    notification: {
      default: '/organizer/notification',
      create: '/organizer/notification/create-notification',
      list: '/organizer/notification/notification-list',
    },
    transactions: {
      default: '/organizer/transactions',
    },
    users: {
      default: '/organizer/user',
      create: '/organizer/user/create-user',
      list: '/organizer/user/user-list',
      pendingList: '/organizer/user/pending-list',
    },
    logout: '/organizer/logout',
  },
};
