export const ChallengesData = [
  {
    id: '1',
    name: 'Complete 5 Orders',
    reward: '100 pts',
    taskType: 'Order Count',
    taskParameters: '5 Orders',
    claimLimit: 50,
    endTime: '2024-07-01',
    tierLimit: 'Silver',
  },
  {
    id: '2',
    name: 'Try the New Burger',
    reward: 'Free Drink',
    taskType: 'Menu Item',
    taskParameters: 'Classic Burger',
    claimLimit: 100,
    endTime: '2024-06-20',
    tierLimit: 'Bronze',
  },
  {
    id: '3',
    name: 'Refer a Friend',
    reward: '200 pts',
    taskType: 'Referral',
    taskParameters: '1 Friend Signup',
    claimLimit: 20,
    endTime: '2024-07-15',
    tierLimit: 'Gold',
  },
  {
    id: '4',
    name: 'Order Dessert',
    reward: '50 pts',
    taskType: 'Menu Item',
    taskParameters: 'Any Dessert',
    claimLimit: 75,
    endTime: '2024-06-30',
    tierLimit: 'Bronze',
  },
  {
    id: '5',
    name: 'Lunch Combo Challenge',
    reward: 'Combo Discount',
    taskType: 'Combo Purchase',
    taskParameters: 'Lunch Combo',
    claimLimit: 40,
    endTime: '2024-07-05',
    tierLimit: 'Silver',
  },
];
