export const TransactionData = [
  {
    _id: '1',
    timestamp: '17-09-2025 14:22',
    transactionType: 'Purchase - In App Order',
    points: '+150',
    user: 'John Doe',
    organizer: 'Emily Carter',
    reference: '2x Burger Combo, 1x Fries',
    status: 'success',
  },
  {
    _id: '2',
    timestamp: '16-09-2025 18:45',
    transactionType: 'Reward Redemption',
    points: '+200',
    user: 'Jane Smith',
    organizer: 'Robert Wilson',
    reference: 'Free Large Pizza',
    status: 'success',
  },
  {
    _id: '3',
    timestamp: '15-09-2025 11:30',
    transactionType: 'Streak Reward',
    points: '+50',
    user: 'Michael Brown',
    organizer: 'Sophia Martinez',
    reference: '7-day streak reward',
    status: 'success',
  },
  {
    _id: '4',
    timestamp: '14-09-2025 09:10',
    transactionType: 'Referral Reward',
    points: '+100',
    user: 'Alice Johnson',
    organizer: 'Daniel Kim',
    reference: 'Referred: Bob Williams',
    status: 'success',
  },
  {
    _id: '5',
    timestamp: '13-09-2025 20:05',
    transactionType: 'Manual Adjustment',
    points: '+50',
    user: 'David Lee',
    organizer: 'Olivia Chen',
    reference: 'Expired points removal',
    status: 'failed',
  },
];
