export const TransactionData = [
  {
    _id: '1',
    purchases: 'Coffee at Downtown Cafe',
    rewardRedemptions: 'Free Muffin',
    transactionType: 'Ticketing',
    timeStamp: '12-01-2025',
    user: 'John Doe',
    organizer: 'Cafe Downtown',
    challengeCompletions: 'Weekly Coffee Challenge',
    points: '+25',
    streakRewards: '3-day streak',
    manualPointGifts: 'Admin Bonus',
    pointExpirations: '-10',
    referrals: 'Invited Jane Doe',
    actions: 'View',
  },
  {
    _id: '2',
    purchases: 'Latte at Central Perk',
    rewardRedemptions: 'Free Cookie',
    transactionType: 'In-app Order',
    timeStamp: '15-01-2025',
    user: 'Emily Clark',
    organizer: 'Central Perk',
    challengeCompletions: 'Monthly Latte Challenge',
    points: '+40',
    streakRewards: '5-day streak',
    manualPointGifts: 'Birthday Gift',
    pointExpirations: '-15',
    referrals: 'Invited John Smith',
    actions: 'View',
  },
  {
    _id: '3',
    purchases: 'Espresso at Bean House',
    rewardRedemptions: 'Free Espresso Shot',
    transactionType: 'Local Purchase',
    timeStamp: '17-01-2025',
    user: 'Michael Lee',
    organizer: 'Bean House',
    challengeCompletions: 'Espresso Expert',
    points: '+30',
    streakRewards: '7-day streak',
    manualPointGifts: 'Special Event',
    pointExpirations: '-20',
    referrals: 'Invited Alice Brown',
    actions: 'View',
  },
  {
    _id: '4',
    purchases: 'Cappuccino at Coffee Corner',
    rewardRedemptions: 'Free Croissant',
    timeStamp: '19-01-2025',
    user: 'Sophia Turner',
    organizer: 'Coffee Corner',
    transactionType: 'Streak Reward',
    challengeCompletions: 'Cappuccino Challenge',
    points: '+35',
    streakRewards: '10-day streak',
    manualPointGifts: 'Referral Bonus',
    pointExpirations: '-5',
    referrals: 'Invited Bob Lee',
    actions: 'View',
  },
];
