export const RewardsData = [
  {
    id: '1',
    purchases: 'Coffee at Downtown Cafe',
    rewardRedemptions: 'Free Muffin',
    challengeCompletions: 'Weekly Coffee Challenge',
    points: '+25',
    streakRewards: '3-day streak',
    manualPointGifts: 'Admin Bonus',
    pointExpirations: '-10',
    referrals: 'Invited Jane Doe',
    actions: 'View',
  },
  {
    id: '2',
    purchases: 'Latte at Central Perk',
    rewardRedemptions: 'Free Cookie',
    challengeCompletions: 'Monthly Latte Challenge',
    points: '+40',
    streakRewards: '5-day streak',
    manualPointGifts: 'Birthday Gift',
    pointExpirations: '-15',
    referrals: 'Invited John Smith',
    actions: 'View',
  },
  {
    id: '3',
    purchases: 'Espresso at Bean House',
    rewardRedemptions: 'Free Espresso Shot',
    challengeCompletions: 'Espresso Expert',
    points: '+30',
    streakRewards: '7-day streak',
    manualPointGifts: 'Special Event',
    pointExpirations: '-20',
    referrals: 'Invited Alice Brown',
    actions: 'View',
  },
  {
    id: '4',
    purchases: 'Cappuccino at Coffee Corner',
    rewardRedemptions: 'Free Croissant',
    challengeCompletions: 'Cappuccino Challenge',
    points: '+35',
    streakRewards: '10-day streak',
    manualPointGifts: 'Referral Bonus',
    pointExpirations: '-5',
    referrals: 'Invited Bob Lee',
    actions: 'View',
  },
];
