import { Order } from './types';

export const MOCK_ACTIVE_ORDERS: Order[] = [
  {
    id: '1',
    deliveryType: 'table',
    location: 'Table 12',
    userName: 'Sarah Johnson',
    userHandle: '@sarahj',
    userEmail: 'sarah.johnson@email.com',
    status: 'preparing',
    totalCost: 42.5,
    isVIP: true,
    notes: 'No croutons on one salad. Extra dressing on the side.',
    createdAt: new Date().toISOString(),
    items: [
      { id: '1-1', name: 'Caesar Salad', quantity: 2, price: 24.0 },
      { id: '1-2', name: 'Grilled Chicken', quantity: 1, price: 18.5 },
    ],
  },
  {
    id: '2',
    deliveryType: 'pickup',
    location: 'Pickup',
    userName: 'Michael Chen',
    userHandle: '@mchen',
    userEmail: 'michael.chen@email.com',
    status: 'sent',
    totalCost: 28.0,
    createdAt: new Date().toISOString(),
    items: [
      { id: '2-1', name: 'Margherita Pizza', quantity: 1, price: 16.0 },
      { id: '2-2', name: 'Tiramisu', quantity: 1, price: 12.0 },
    ],
  },
  {
    id: '3',
    deliveryType: 'table',
    location: 'Table 5',
    userName: 'Emma Williams',
    userHandle: '@emmaw',
    userEmail: 'emma.williams@email.com',
    status: 'waiting-payment',
    totalCost: 87.25,
    paymentType: 'pay-later',
    createdAt: new Date().toISOString(),
    items: [
      { id: '3-1', name: 'Ribeye Steak', quantity: 2, price: 64.0 },
      { id: '3-2', name: 'House Wine', quantity: 2, price: 18.0 },
      { id: '3-3', name: 'Chocolate Cake', quantity: 1, price: 9.25 },
    ],
  },
  {
    id: '4',
    deliveryType: 'table',
    location: 'Table 8',
    userName: 'James Anderson',
    userHandle: '@janderson',
    userEmail: 'james.anderson@email.com',
    status: 'preparing',
    totalCost: 56.75,
    isPreorder: true,
    createdAt: new Date().toISOString(),
    items: [
      { id: '4-1', name: 'Fish & Chips', quantity: 2, price: 32.0 },
      { id: '4-2', name: 'Cola', quantity: 2, price: 8.0 },
      { id: '4-3', name: 'Ice Cream', quantity: 2, price: 16.75 },
    ],
  },
  {
    id: '5',
    deliveryType: 'togo',
    location: 'To Go',
    userName: 'Olivia Martinez',
    userHandle: '@oliviam',
    userEmail: 'olivia.martinez@email.com',
    status: 'preparing',
    totalCost: 15.5,
    createdAt: new Date().toISOString(),
    items: [{ id: '5-1', name: 'Club Sandwich', quantity: 1, price: 15.5 }],
  },
  {
    id: '6',
    deliveryType: 'table',
    location: 'Table 3',
    userName: 'David Brown',
    userHandle: '@dbrown',
    userEmail: 'david.brown@email.com',
    status: 'preparing',
    totalCost: 34.0,
    createdAt: new Date().toISOString(),
    items: [
      { id: '6-1', name: 'Spaghetti Carbonara', quantity: 1, price: 22.0 },
      { id: '6-2', name: 'Garlic Bread', quantity: 1, price: 12.0 },
    ],
  },
  {
    id: '7',
    deliveryType: 'pickup',
    location: 'Pickup',
    userName: 'Sophia Taylor',
    userHandle: '@sophiat',
    userEmail: 'sophia.taylor@email.com',
    status: 'sent',
    totalCost: 45.25,
    isVIP: true,
    createdAt: new Date().toISOString(),
    items: [
      { id: '7-1', name: 'Sushi Roll', quantity: 2, price: 28.0 },
      { id: '7-2', name: 'Miso Soup', quantity: 1, price: 8.0 },
      { id: '7-3', name: 'Green Tea', quantity: 1, price: 9.25 },
    ],
  },
  {
    id: '8',
    deliveryType: 'table',
    location: 'Table 15',
    userName: 'Liam Wilson',
    userHandle: '@liamw',
    userEmail: 'liam.wilson@email.com',
    status: 'preparing',
    totalCost: 68.5,
    notes: 'Extra BBQ sauce. No onions in coleslaw.',
    createdAt: new Date().toISOString(),
    items: [
      { id: '8-1', name: 'BBQ Ribs', quantity: 2, price: 46.0 },
      { id: '8-2', name: 'Coleslaw', quantity: 2, price: 12.0 },
      { id: '8-3', name: 'Lemonade', quantity: 2, price: 10.5 },
    ],
  },
];

export const MOCK_PREORDERS: Order[] = [
  {
    id: 'p1',
    deliveryType: 'table',
    location: 'Table 20',
    userName: 'Isabella Garcia',
    userHandle: '@isabellag',
    userEmail: 'isabella.garcia@email.com',
    status: 'pending',
    totalCost: 38.0,
    isVIP: true,
    isPreorder: true,
    createdAt: new Date().toISOString(),
    items: [
      { id: 'p1-1', name: 'Seafood Paella', quantity: 1, price: 28.0 },
      { id: 'p1-2', name: 'Sangria', quantity: 1, price: 10.0 },
    ],
  },
  {
    id: 'p2',
    deliveryType: 'table',
    location: 'Table 22',
    userName: 'Noah Robinson',
    userHandle: '@noahr',
    userEmail: 'noah.robinson@email.com',
    status: 'pending',
    totalCost: 52.75,
    isPreorder: true,
    createdAt: new Date().toISOString(),
    items: [
      { id: 'p2-1', name: 'Lobster Tail', quantity: 2, price: 42.0 },
      { id: 'p2-2', name: 'Champagne', quantity: 1, price: 10.75 },
    ],
  },
  {
    id: 'p3',
    deliveryType: 'table',
    location: 'Table 25',
    userName: 'Ava Lee',
    userHandle: '@avalee',
    userEmail: 'ava.lee@email.com',
    status: 'pending',
    totalCost: 64.0,
    isVIP: true,
    isPreorder: true,
    createdAt: new Date().toISOString(),
    items: [
      { id: 'p3-1', name: 'Filet Mignon', quantity: 2, price: 52.0 },
      { id: 'p3-2', name: 'Red Wine', quantity: 2, price: 12.0 },
    ],
  },
];

export const MOCK_PAST_ORDERS: Order[] = [
  {
    id: 'past1',
    deliveryType: 'table',
    location: 'Table 7',
    userName: 'Ethan Moore',
    userHandle: '@ethanm',
    userEmail: 'ethan.moore@email.com',
    status: 'paid',
    totalCost: 31.5,
    completedAt: 'Today, 2:45 PM',
    createdAt: new Date().toISOString(),
    items: [
      { id: 'past1-1', name: 'Burger & Fries', quantity: 1, price: 18.5 },
      { id: 'past1-2', name: 'Milkshake', quantity: 1, price: 13.0 },
    ],
  },
  {
    id: 'past2',
    deliveryType: 'pickup',
    location: 'Pickup',
    userName: 'Mia Thomas',
    userHandle: '@miat',
    userEmail: 'mia.thomas@email.com',
    status: 'canceled',
    totalCost: 12.0,
    completedAt: 'Today, 1:30 PM',
    createdAt: new Date().toISOString(),
    items: [{ id: 'past2-1', name: 'Greek Salad', quantity: 1, price: 12.0 }],
  },
];
